server:
  port: 3333

spring:
  application:
    name: employee-service

eureka:
  client:
    fetch-registry:
    service-url:
      default: http://localhost:8761/eureka
  insance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 3
